#!/usr/bin/env python
# expects https://github.com/InspectorMustache/base16-builder-python to be installed and `pybase16 update`
import os
import shutil
import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory
from utils import repo_toplevel_dir


def regenerate():
    toplevel_dir = repo_toplevel_dir()
    os.chdir(toplevel_dir)

    with TemporaryDirectory() as tmpdir:
        subprocess.run(["pybase16", "build", "--output", tmpdir])
        shutil.copytree(
            Path(tmpdir) / "vim" / "colors",
            Path(toplevel_dir) / "colors",
            dirs_exist_ok=True,
        )


if __name__ == "__main__":
    regenerate()
